version: "3"
services:
  user-service-app:
    image: user-service-app
    restart: always
    build: .
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysql-service
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  mysql-service:
    container_name: mysql-service
    image: mysql:5.7
    volumes:
      -  /home/user/Desktop/db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: userservicedb
      MYSQL_ROOT_PASSWORD: root
